### PR TITLE
87: Add system test to check if job timeout feature correctly cancels…

### PR DESCRIPTION
**Pull request by lfse-slafleur**
… timed out jobs.

### CODE REVIEW

**Comment by cwang39403** [comment]
@lfse-slafleur Thanks for adding a system test for this feature! Do you think it is feasible to add a system test for `postgres_job_manager` as well? If so, I would like to add it too.

Wondering which system test script should be used if testing locally. 
If I use `./scripts/test_system.sh`, no errors are returned.
If I use `./system_test/ci/linux/run.sh` then 2 out of 11 test cases failed
image

**Comment by lfse-slafleur** [comment]
@cwang39403 Testing that specific feature is a bit more difficult. We would need to reconfigure the orchestrator for that specific test somehow which is currently not supported in the system tests. It is the same value for all jobs and we want to ensure that changing the value to an artificial low value to trigger the clean up quickly, is difficult.


`If I use ./scripts/test_system.sh, no errors are returned.` <-- This one is setup the test environment and run the tests. Complete standalone script.

`If I use ./system_test/ci/linux/run.sh then 2 out of 11 test cases failed` <-- Assume an environment is online and run ONLY the system tests. Probably, there was no OMOTES active on your system. Curious, which 2 tests succeeded?

**Comment by cwang39403** [comment]
@lfse-slafleur
> Assume an environment is online and run ONLY the system tests. Probably, there was no OMOTES active on your system. Curious, which 2 tests succeeded?

I run this command according to the `system_tests/README`. So the OMOTES system is running locally. The 2 failed test cases are `test__simulator__hapy_path` and `test__simulator__job_timeout_working`, also in the screenshot above.

**Review by MarkTNO — APPROVED** [review]

**Comment by lfse-slafleur** [comment]
> @lfse-slafleur
> 
> > Assume an environment is online and run ONLY the system tests. Probably, there was no OMOTES active on your system. Curious, which 2 tests succeeded?
> 
> I run this command according to the `system_tests/README`. So the OMOTES system is running locally. The 2 failed test cases are `test__simulator__hapy_path` and `test__simulator__job_timeout_working`, also in the screenshot above.

Cheers! Based on the result it appears that the version of the simulator may be lagging. Can you confirm you not only pulled the latest OMOTES but also ran both `./scripts/setup.sh` & `./scripts/start.sh`? This should ensure that the latest versions of simulator and such are running. To double check, you can check which version of images are running with `docker ps -a`.

**Pull request merged**
